/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#ifndef _P2P_H_RPCGEN
#define _P2P_H_RPCGEN

#define RPCGEN_VERSION	199506

#include <rpc/rpc.h>


struct peerfile {
	int peerid;
	char *filename;
};
typedef struct peerfile peerfile;
#ifdef __cplusplus
extern "C" bool_t xdr_peerfile(XDR *, peerfile*);
#elif __STDC__
extern  bool_t xdr_peerfile(XDR *, peerfile*);
#else /* Old Style C */
bool_t xdr_peerfile();
#endif /* Old Style C */


#define PEER_PROG ((rpc_uint)0x20000000)
#define PEER_VER ((rpc_uint)1)

#ifdef __cplusplus
#define registry ((rpc_uint)1)
extern "C" int * registry_1(peerfile *, CLIENT *);
extern "C" int * registry_1_svc(peerfile *, struct svc_req *);

#elif __STDC__
#define registry ((rpc_uint)1)
extern  int * registry_1(peerfile *, CLIENT *);
extern  int * registry_1_svc(peerfile *, struct svc_req *);

#else /* Old Style C */
#define registry ((rpc_uint)1)
extern  int * registry_1();
extern  int * registry_1_svc();
#endif /* Old Style C */

#endif /* !_P2P_H_RPCGEN */
