/*
 * Please do not edit this file.
 * It was generated using rpcgen.
 */

#include "p2p.h"

bool_t
xdr_peerfile(XDR *xdrs, peerfile *objp)
{

	if (!xdr_int(xdrs, &objp->peerid))
		return (FALSE);
	if (!xdr_string(xdrs, &objp->filename, ~0))
		return (FALSE);
	return (TRUE);
}
